### ISSUE TITLE
Scene exceptions missing for Season 2

### ISSUE THREAD

**Issue by GeckoOBac** [SickChill/sickchill.github.io#27]
The following two shows are missing their Season 2 listing in the scene exceptions menu.
**Radiant** (https://www.thetvdb.com/series/radiant);
- Radiant S2

**Isekai Quartet** (https://www.thetvdb.com/series/isekai-quartet):
- Isekai Quartet 2nd Season
- Isekai Quartet S2
- Isekai Quartet2

**Comment by miigotu** [comment]
Please add them to the json https://github.com/SickChill/sickchill.github.io/tree/master/scene_exceptions
I could never keep up with all of these on my own, you'll have to submit a PR

**Comment by BenjV** [comment]
@GeckoOBac 
Don't add them in SickChill.
Go to the tvdb website, log in and add them there.
The tvdb is maintained by the community, so be a member and update tvdb.

**Comment by GeckoOBac** [comment]
@BenjV as far as I can tell the tvdb takes exception with naming seasons something like "S2" or "Second Season", which means that in many cases, such as the two above, editing the indexer is not a viable solution.

**Comment by miigotu** [comment]
https://github.com/SickChill/sickchill.github.io/tree/master/scene_exceptions
