### ISSUE TITLE
Can't find show

### ISSUE THREAD

**Issue by Jimgitsit** [SickChill/sickchill.github.io#29]
Sickchill can't find episodes of Seth Meyers on nzbplanet. The API request is 

https://api.nzbplanet.net/api?apikey=8d9cfb65ca45019bc870c5cb458f3e6f&tvdbid=270262&maxage=600&cat=5000%2C5040%2C5030%2C5045&limit=100&t=tvsearch&offset=0&season=7&ep=55

I tried setting the show to air-by-date which produced the API request 

https://api.nzbplanet.net/api?apikey=**********&tvdbid=270262&season=2020&maxage=600&cat=5000%2C5040%2C5030%2C5045&limit=100&t=tvsearch&offset=0&ep=01%2F27

But still no luck. The episodes are definitely there. I have downloaded the nzbs manually. I think it need to try searching by title or something. Worked fine on nzbtortuga, before they shut down :(

**Comment by miigotu** [comment]
This is not the correct repo for this issue, but likely the category or tvdbid is not set on nzbplanet like you expect.
SickChill/SickChill
