### ISSUE TITLE
Dr Who/Star Trek classic overwritten by new series

### ISSUE THREAD

**Issue by ejlkemper** [SickChill/sickchill.github.io#69]
Looking at Dr Who (classic!) I run into issue that the new series ones are sometimes downloaded and overwrite the classic episode?!

In "scene exception" I see in Shows both versions, but cannot remove the one which does not have the word "classic" in it.

Or am I doing something wrong?

**Comment by BKSteve** [comment]
There are the naming conventions and eventually the new series drops the year descriptor from the file name. Doctor Who 2005 hours to Doctor Who and they overlap.
So to find the latest episodes you need to add the exception to be just Doctor Who for the new stuff. Names then conflict and the processor logic then overwrites the old series files. 
I personally remove old series from SC to avoid this, only adding temporarily to post process any updated files I've manually collected to the old series.

**Comment by ejlkemper** [comment]
Ok, to bad, any hints on how to find the missing/ruined episods of the classic DW? :-)

**Comment by BKSteve** [comment]
The changed ones will have a much newer file date, or at least different to your `original` DW eps.
