### ISSUE TITLE
Wiki on SickChill points to wrong sickchill.github.io repo

### ISSUE THREAD

**Issue by didyouexpectthat** [SickChill/sickchill.github.io#7]
Hi @miigotu 
https://github.com/SickChill/SickChill/wiki/Scene-exceptions-and-numbering
On this Wiki page, you link to the Scene Exceptions

> So when you have a show that requires a manual scene exception please submit a Pull Request to the scene exception list at [SickChill.GitHub.io](https://github.com/SickChill/sick-chill.github.io/blob/master/sb_tvdb_scene_exceptions/exceptions.txt). This also helps other users that experience this problem.

But the URL in that "SickChill.GitHub.io" is currently:
`https://github.com/SickChill/sick-chill.github.io/blob/master/sb_tvdb_scene_exceptions/exceptions.txt`

Which will take you to the wrong page. Need to remove the hyphen in `sick-chill.github.io`

Replace with
`https://github.com/SickChill/sickchill.github.io/blob/master/sb_tvdb_scene_exceptions/exceptions.txt`

Didn't have edit rights so I am posting an issue. 
Thanks.

**Comment by miigotu** [comment]
Fixed
